import type { Metadata } from "next";
import "./globals.css";  
import ThemeProvider from "@/context/theme/Theme.provider";
import FireBaseProvider from "@/context/firebase/firebase.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased dark:bg-black`}>
        <ThemeProvider>
          <FireBaseProvider>{children}</FireBaseProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
