import ThemeProvider from "@/context/theme/Theme.provider";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { routing } from "../../i18n/routing";
import { getMessages } from "next-intl/server";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  // Ensure the type assertion is correct and refers to your i18n locale type
  if (!routing.locales.includes(locale)) {
    notFound();
  }
  const messages = await getMessages();

  return (
    <html lang="en">
      <body className={` antialiased dark:bg-black`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider>{children}</ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
