import ThemeProvider from "@/context/theme/Theme.provider";
import "./globals.css";
import FirebaseProvider from "@/context/firebase/firebase.provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased dark:bg-black`}>
        <ThemeProvider>
          <FirebaseProvider>
            {children}
          </FirebaseProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
